services:
  dothattast_be:
    build: .
    ports:
      - "0.0.0.0:10000:10000"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_EMB: ${DB_EMB}
    restart: always