ktor {

    deployment {
        host = 0.0.0.0
        port = 10000
        port = ${?PORT}
    }

    application {
        modules = [ homeaq.dothattask.ApplicationKt.module ]
    }

    postgres {
        url = ${DB_URL}
        user = ${DB_USER}
        password = ${DB_PASSWORD}
    }

    database {
            embedded = ${DB_EMB}
        }
}