package homeaq.dothattask.data.DBSchema

import homeaq.dothattask.data.TableCreationAndSeed.ITableFactory
import homeaq.dothattask.data.TableCreationAndSeed.ITableSeed
import java.sql.Connection

/**
 * Global registry of every task category ever created in the system.
 *
 * The pre-seeded ids 1=Social, 2=Career, 3=Health match the codes the legacy
 * `TaskCategory` enum used so existing rows in `tasks.category` (an INTEGER
 * column) keep referencing the right category after the migration.
 *
 * Names are case-insensitive unique: the repository normalizes new names to
 * "First-letter capital, rest lowercase" before persisting. The column itself
 * is plain VARCHAR; the uniqueness check is done in code on the lowercase
 * form so "Social"/"social"/"SOCIAL" all collide.
 */
sealed class CategoriesSchema {
    companion object {
        const val DEFAULT_COLOR = "#7E57C2"

        // GENERATED BY DEFAULT (not ALWAYS) so the seeder can pin the
        // default-category ids to 1/2/3 to match legacy `tasks.category` codes.
        const val CREATE_TABLE_CATEGORIES_H2 =
            "CREATE TABLE IF NOT EXISTS CATEGORIES (" +
                    "ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "name VARCHAR(150) NOT NULL," +
                    "color VARCHAR(9) NOT NULL DEFAULT '$DEFAULT_COLOR'," +
                    "is_default BOOLEAN NOT NULL DEFAULT FALSE)"

        const val CREATE_TABLE_CATEGORIES_PG =
            "CREATE TABLE IF NOT EXISTS CATEGORIES (" +
                    "ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "name VARCHAR(150) NOT NULL," +
                    "color VARCHAR(9) NOT NULL DEFAULT '$DEFAULT_COLOR'," +
                    "is_default BOOLEAN NOT NULL DEFAULT FALSE)"

        // Seed default categories with fixed ids matching the legacy enum codes.
        val DEFAULTS = listOf(
            DefaultCategory(1, "Social", "#42A5F5"),
            DefaultCategory(2, "Career", "#26A69A"),
            DefaultCategory(3, "Health", "#EF5350"),
        )
    }

    data class DefaultCategory(val id: Int, val name: String, val color: String)
}

private fun seedDefaultCategoriesH2(connection: Connection) {
    val merge = connection.prepareStatement(
        "MERGE INTO categories (id, name, color, is_default) KEY(id) VALUES (?, ?, ?, TRUE)"
    )
    CategoriesSchema.DEFAULTS.forEach { d ->
        merge.setInt(1, d.id)
        merge.setString(2, d.name)
        merge.setString(3, d.color)
        merge.executeUpdate()
    }
    // Bump the IDENTITY sequence past the manually-seeded ids so the next
    // user-supplied INSERT (without explicit id) doesn't collide with them.
    val maxId = CategoriesSchema.DEFAULTS.maxOf { it.id }
    connection.createStatement().executeUpdate(
        "ALTER TABLE categories ALTER COLUMN id RESTART WITH ${maxId + 1}"
    )
}

private fun seedDefaultCategoriesPg(connection: Connection) {
    val upsert = connection.prepareStatement(
        "INSERT INTO categories (id, name, color, is_default) VALUES (?, ?, ?, TRUE) " +
                "ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, color = EXCLUDED.color, is_default = TRUE"
    )
    CategoriesSchema.DEFAULTS.forEach { d ->
        upsert.setInt(1, d.id)
        upsert.setString(2, d.name)
        upsert.setString(3, d.color)
        upsert.executeUpdate()
    }
    // After seeding fixed ids, bump the identity sequence past them so future
    // INSERTs without explicit id don't collide.
    connection.createStatement().executeUpdate(
        "SELECT setval(pg_get_serial_sequence('categories', 'id'), GREATEST(MAX(id), 0)) FROM categories"
    )
}

class CategoriesTableFactoryH2 : ITableFactory {
    override fun createTable(connection: Connection) {
        connection.createStatement().executeUpdate(CategoriesSchema.CREATE_TABLE_CATEGORIES_H2)
        seedDefaultCategoriesH2(connection)
    }
}

class CategoriesTableFactoryPostgres : ITableFactory {
    override fun createTable(connection: Connection) {
        connection.createStatement().executeUpdate(CategoriesSchema.CREATE_TABLE_CATEGORIES_PG)
        seedDefaultCategoriesPg(connection)
    }
}

class CategoriesTableSeedH2 : ITableSeed {
    override fun seed(connection: Connection) {}
}

class CategoriesTableSeedPostgres : ITableSeed {
    override fun seed(connection: Connection) {}
}
